### ISSUE TITLE
提示No module named 'kanman_com'

### ISSUE THREAD

**Issue by TheEnd233** [Amd794/kanleying#1]
直接把仓库clone下来后运行kanleying.py提示以下错误

D:\develop\python3.7\python.exe D:/Code/Git-Project-Learn/kanleying-master/kanleying.py
文件不存在
漫画地址:https://www.kanman.com/107682/ 
https://www.kanman.com/ kanman
Traceback (most recent call last):
  File "D:/Code/Git-Project-Learn/kanleying-master/kanleying.py", line 417, in <module>
    main()
  File "D:/Code/Git-Project-Learn/kanleying-master/kanleying.py", line 374, in main
    detail_dicts = Comic.get_detail_dicts(url, host_url, host_key)
  File "D:/Code/Git-Project-Learn/kanleying-master/kanleying.py", line 131, in get_detail_dicts
    from kanman_com import Kanman
ModuleNotFoundError: No module named 'kanman_com'

请问是不是项目缺少了kanman_com.py文件，我该如何解决？

**Comment by cmdragon** [comment]
I did not upload the file for some reason
