### ISSUE TITLE
NotADirectoryError: [WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by keeycheng** [Amd794/kanleying#2]
git clone 后， 要下载漫画， 可以拿到集数，可是回车后就有error了。

F:\Comic\kanleying>python kanleying.py
漫画地址:https://www.cocomanhua.com/12202/
https://www.cocomanhua.com/ cocomanhua
该漫画共887章节
>>>:
char:[]  index:[]
Traceback (most recent call last):
  File "F:\Comic\kanleying\kanleying.py", line 417, in <module>
    main()
  File "F:\Comic\kanleying\kanleying.py", line 413, in main
    run(detail_dicts.pop())
  File "F:\Comic\kanleying\kanleying.py", line 380, in run
    images_dict = Comic.get_images_url(detail_dict)
  File "F:\Comic\kanleying\kanleying.py", line 263, in get_images_url
    images_url = eval(data.get(Comic.current_host_key, '[]'))
  File "<string>", line 1, in <module>
  File "F:\Comic\kanleying\site\cocomanhua_com.py", line 21, in _cocomanhua
    images_url = ctx.eval(f'getArr("{data}")')
  File "C:\Python39\lib\site-packages\execjs\_abstract_runtime_context.py", line 27, in eval
    return self._eval(source)
  File "C:\Python39\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Python39\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Python39\lib\site-packages\execjs\_external_runtime.py", line 87, in _exec_
    output = self._exec_with_pipe(source)
  File "C:\Python39\lib\site-packages\execjs\_external_runtime.py", line 99, in _exec_with_pipe
    p = Popen(cmd, stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd=self._cwd, universal_newlines=True)
  File "C:\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid

**Comment by cmdragon** [comment]
Raised when a directory operation (such as os.listdir()) is requested on something which is not a directory. Corresponds to errno ENOTDIR. The comic you want to download does not exist or has been deleted by the webmaster

**Comment by keeycheng** [comment]
Thanks for the update, but the comic still exists on the website, the same error happen on some of the other sample sites you provided as well, except for 
http://www.pufei8.com/manhua/7/

**Comment by cmdragon** [comment]
My machine cannot reproduce your problem, you can try to upgrade Python IDLE or create a folder manually. 
Format: kanleying/comic_title/chapter/
![image](https://user-images.githubusercontent.com/39700024/103976163-f2879d80-51b0-11eb-9a5c-0254ba2b5668.png)

**Comment by keeycheng** [comment]
Hi Amd, 

tried again, and with debugging on this time. 

![image](https://user-images.githubusercontent.com/33142777/103984727-a04f7800-51c2-11eb-87f7-b700232445e8.png)


It looks like it doesnt have the comic title , i was trying to download from cocomanhua, do you think this is the issue here?

![image](https://user-images.githubusercontent.com/33142777/103984775-b6f5cf00-51c2-11eb-8523-b0294a362869.png)

**Comment by cmdragon** [comment]
If you want to download comics from cocomanhua, you must install package.json, which encrypts the data. 
You can cd js and then run npm install
