### ISSUE TITLE
需要登錄才能觀看的站點怎麼登錄。

### ISSUE THREAD

**Issue by saicbs** [Amd794/kanleying#8]
需要會員才能觀看的VIP章節，不登陸沒辦法用腳本下載。
有需要輸入cookie的地方嗎？

**Comment by saicbs** [comment]
cookie已經解決了，現在又有新的問題，爬漫畫爬著爬著經常出 現下面這種錯誤

`Exception in thread Thread-131:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "I:\kanleying-master\threading_download_images.py", line 83, in download_images
    if '18comic3' in image_url:
TypeError: argument of type 'NoneType' is not iterable`
